config/routes.rb
Patients::Application.routes.draw do

  root to: 'static_pages#home'
  match '/', to: 'static_pages#home'
  match '/home', to: 'static_pages#home'

  resources :locations
  resources :patients

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :code, :name

  has_many :patients
  accepts_nested_attributes_for :patients

  validates :name, presence: true, length: { maximum: 80 }
  validates :code, length: { maximum: 10 }


end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :id, :birth, :first_name, :gender, :last_name, :middle_name, :status, :viewed_count, :location_id, :is_deleted
  belongs_to :location

  default_scope order: 'patients.created_at DESC'

  validates :first_name, presence: true, length: { maximum: 30 }
  validates :middle_name, length: { maximum: 10}
  validates :last_name, presence: true, length: { maximum: 30 }
  validates :status, presence: true
  validates :location_id, presence: true

  validates_inclusion_of :gender,
            :in => %w{ Male Female Notavailable},
            :message =>"should be 'Male' or 'Female' or 'Notavailable' "

  validates_inclusion_of :status,
            :in => %w{ Initial Referred Treatment Closed },
            :message =>"should be in 'Initial Referred Treatment Closed' "
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_locate

  def set_locate
      if params[:locale] && I18n.available_locales.include?(params[:locale].to_sym)
          session[:locale] = params[:locale]	
      end
      I18n.locale = session[:locale] || extract_locale_accept_language_header
  end

  def extract_locale_accept_language_header
  	#request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
      'en'
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # GET /patients
  # GET /patients.json

  def index
    @patients = Patient.find(:all, :conditions =>{ :is_deleted => false })

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patients }
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.find(params[:id])
    if @patient.is_deleted?
      @patient = nil
    else
      Patient.update(@patient.id, :viewed_count => @patient.viewed_count +=1)
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/new
  # GET /patients/new.json
  def new
    @patient = Patient.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.json
  def create
    @location = Location.find(params[:patient][:location_id] )
    @patient = @location.patients.create(params[:patient]);
    @patient.is_deleted = false
    @patient.viewed_count = 0

    #@patient = Patient.new(params[:patient])
    #@patient =Patient.new(params[:patient]);
    # patient.location_id = params[:location_id]


    respond_to do |format|
      if @location.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render json: @patient, status: :created, location: @patient }
      else
        format.html { render action: "new" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.json
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient = Patient.find(params[:id])
    #@patient.destroy
    Patient.update(@patient.id, :is_deleted => true)
    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@locations = Location.all
  	@patients = Patient.find(:all, :conditions =>{ :is_deleted => false })
  	@onTreatment = Patient.find(:all, :conditions =>{ :is_deleted => false, :status => "Treatment" })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	 <div class="navbar-inner">
	 	<div class="container">
	 		<%= link_to "patients", '/', id: "logo" %>
	 		<nav>
	 			<ul class="nav pull-right">
	 				<% if session[:locale] == "en" %>
				                <li><%= link_to "[Chinese]", :controller => controller.controller_name,
				                        :action => controller.action_name, :locale => "zh" %></li>
				              <% else %>
				                <li><%= link_to "[英文]", :controller => controller.controller_name,
				                        :action => controller.action_name, :locale => "en" %></li>
				              <% end %>
	 			</ul>
	 		</nav>
	 	</div>
	 </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Patients</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |key,value| %>
	<div id="flash_message" class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
	<%= yield %>
	<%= render 'layouts/footer' %> 
	<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="span4 offset4">
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.number_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<div class="clear"></div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>
<div class="center">
<%= link_to I18n.t('show'), @location %> |
<%= link_to I18n.t('back'), locations_path %>
</div>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.name %></td>
    <td><%= location.code %></td>
    <td><%= link_to I18n.t('show'), location, class: "btn btn-primary" %></td>
    <td><%= link_to I18n.t('edit'), edit_location_path(location), class: "btn btn-info" %></td>
    <td><%= link_to I18n.t('delete'), location, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to I18n.t('new'), new_location_path,class: "btn btn-large btn-primary" %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<div class="center">
<%= link_to I18n.t('back'), locations_path %>
</div>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>Code:</b>
  <%= @location.code %>
</p>

<%= link_to I18n.t('edit'), edit_location_path(@location) %> |
<%= link_to I18n.t('back'), locations_path %>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="span4 offset4">
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :birth %>
    <%= f.date_select :birth %>
  </div>
  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :location_id %>
    <%= f.number_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<div class="clear"></div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>
<div class="center">
<%= link_to I18n.t('show'), @patient %> |
<%= link_to I18n.t('back'), patients_path %>
</div>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table class="table">
  <tr>
    <th>MR</th>
    <th>Name</th>
    <th>Birth</th>
    <th>Gender</th>
    <th>Status</th>
    <th>Viewed count</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @patients.each do |patient| %>
  <tr>
    <td><%= "MR"+"0"*(6-patient.id.to_s.length)+patient.id.to_s %></td>
    <td><%= patient.last_name+', '+patient.first_name+' '+patient.middle_name %></td>
    <td><%= patient.birth %></td>
    <td><%= patient.gender %></td>
    <td><%= patient.status %></td>
    <td><%= patient.viewed_count %></td>
    <td><%= patient.location.name %></td>
    <td><%= link_to I18n.t('show'), patient, class: "btn btn-primary" %></td>
    <td><%= link_to I18n.t('edit'), edit_patient_path(patient), class: "btn btn-info" %></td>
    <td><%= link_to I18n.t('delete'), patient, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to I18n.t('new'), new_patient_path,class: "btn btn-large btn-primary" %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<div class="center">
<%= link_to I18n.t('back'), patients_path %>
</div>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @patient.first_name %>
</p>

<p>
  <b>Middle name:</b>
  <%= @patient.middle_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @patient.last_name %>
</p>

<p>
  <b>Birth:</b>
  <%= @patient.birth %>
</p>

<p>
  <b>Gender:</b>
  <%= @patient.gender %>
</p>

<p>
  <b>Status:</b>
  <%= @patient.status %>
</p>

<p>
  <b>Viewed count:</b>
  <%= @patient.viewed_count %>
</p>

<p>
  <b>Location:</b>
  <%= @patient.location.name %>
</p>

<%= link_to I18n.t('edit'), edit_patient_path(@patient) %> |
<%= link_to I18n.t('back'), patients_path %>

app/views/shared/_locations.html.erb
<div class="m10 right">
	<span><%= link_to(I18n.t('new'),'/locations/new') %>&nbsp;</span>
	<span><%= link_to(I18n.t('more'),'/locations') %>>></span>
</div>
<% if (!@locations.nil?) && @locations.any? %>
	<table class="table">
		<tr>
		<td>NO.</td>
		<td>Name</td>
		<td>Code</td>
		</tr>
		<% @locations.each_with_index do |location, i | %>
		<tr>
		<td><%= i+1 %></td>
		<td><%= location.name %></td>
		<td><%= location.code %></td>
		</tr>
		<% end %>
	</table>
<% else %>
	<div> locations is null </div>
<% end %>

app/views/shared/_onTreatment_patients.html.erb
<div class="m10 right">
<span><%= link_to(I18n.t('new'),'/patients/new') %>&nbsp;</span>
<span><%= link_to(I18n.t('more'),'/patients') %>>></span>
</div>
<% if (!@onTreatment.nil?) && @onTreatment.any? %>
	<table class="table">
		<tr>
		<td>NO.</td>
		<td>MR</td>
		<td>Name</td>
		<td>Status</td>
		<td>ViewCount</td>
		</tr>
		<% @onTreatment.each_with_index do |patient, i | %>
		<tr>
			<td><%= i+1 %></td>
			<td><%= "MR"+"0"*(6-patient.id.to_s.length)+patient.id.to_s %></td>
			<td><%= link_to patient.last_name+', '+patient.first_name+' '+patient.middle_name, "patients/#{patient.id}" %></td>
			<td><%= patient.status %></td>
			<td><%= patient.viewed_count %></td>
		</tr>
		<% end %>
	</table>
<% else %>
	<div> onTreatment patients is null </div>
<% end %>

app/views/shared/_patients.html.erb
<div class="m10 right">
<span><%= link_to(I18n.t('new'),'/patients/new') %>&nbsp;</span>
<span><%= link_to(I18n.t('more'),'/patients') %>>></span>
</div>
<% if (!@patients.nil?) && @patients.any? %>
	<table class="table">
		<tr>
		<td>NO.</td>
		<td>MR</td>
		<td>Name</td>
		<td>Status</td>
		<td>ViewCount</td>
		</tr>
		<% @patients.each_with_index do |patient, i | %>
		<tr>
			<td><%= i+1 %></td>
			<td><%= "MR"+"0"*(6-patient.id.to_s.length)+patient.id.to_s %></td>
			<td><%= link_to patient.last_name+', '+patient.first_name+' '+patient.middle_name, "patients/#{patient.id}" %></td>
			<td><%= patient.status %></td>
			<td><%= patient.viewed_count %></td>
		</tr>
		<% end %>
	</table>
<% else %>
	<div> patients is null </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="row">
	<aside class="span4">
		<section>
			<h1><%= I18n.t('locations') %></h1>
		</section>
		<section>
			<%= render 'shared/locations' %>
		</section>
	</aside>
	<aside class="span8">
		<section>
			<h1><%= I18n.t('onTreatment') %></h1>
		</section>
		<section>
			<%= render 'shared/onTreatment_patients' %>
		</section>
		<br />
		<section>
			<h1><%= I18n.t('patients') %></h1>
		</section>
		<section>
			<%= render 'shared/patients' %>
		</section>
	</aside>
</div>